#!/usr/bin/bash

#
# TODO: check if it needs to run all `scripts` and `after`,
# only `scripts`,
# or only `after`;
#

script_dir="$(
  cd "$(
    dirname "${BASH_SOURCE[0]}"
  )" &> /dev/null && pwd
)"
echo "$script_dir"

filter=""
dry=""

while [[ $# > 0 ]]; do
  if [[ $1 == "--dry" ]]; then
    dry="1"
  else
    filter="$1"
  fi
  shift
done

log () {
  if [[ $dry = "1" ]]; then
    echo "[DRY_RUN]: $@"
  else
    echo "$@"
  fi
}

execute () {
  log "execute $@"
  if [[ $dry = "1" ]]; then
    return
  fi

  "$@"
}

echo "Run: dir $script_dir -- filter \"$filter\""

cd $script_dir
scripts=$(
  find ./scripts -maxdepth 1 -mindepth 1 -executable -type f | sort
)

for script in $scripts; do
  if echo "$script" | grep -qv "$filter"; then
    log "filtering $script"
    continue
  fi

  execute $script
done

after_scripts=$(
  find ./after -maxdepth 1 -mindepth 1 -executable -type f | sort
)

for after_script in $after_scripts; do
  if echo "$after_script" | grep -qv "$filter"; then
    log "filtering $after_script"
    continue
  fi

  execute $after_script
done
