#!/usr/bin/bash

git clone git@github.com:gabrielforster/dotfiles /tmp/dotfiles

cp -r /tmp/dotfiles/tmux/.tmux.conf ~/.tmux.conf
cp -r /tmp/dotfiles/zsh/.zshrc ~/.zshrc
cp -r /tmp/dotfiles/git/.gitconfig ~/.gitconfig
cp -r /tmp/dotfiles/config/.config/*** ~/.config/
